import 'package:oev_mobile_app/domain/entities/course/course_model.dart';

List<Course> courseList() {
  return [
    Course(
      id: 1,
      name: 'Introducción a Java',
      description: 'Un curso introductorio',
      benefits: 'Desarrollarás habilidades en Java.',
      targetAudience: 'Estudiantes principiantes en programación.',
      imageUrl: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
      category: 'Programación',
      level: 'Básico',
      price: 49.99,
      duration: null,
      totalLessons: null,
      totalStudents: 0,
      favorite: null,
      status: null,
      creationDate: DateTime.parse('2025-02-05T21:50:55.850705'),
      lastUpdate: null,
      userId: 2,
    ),
    Course(
      id: 2,
      name: 'Flutter desde Cero',
      description: 'Aprende a desarrollar apps con Flutter.',
      benefits: 'Construirás aplicaciones móviles multiplataforma.',
      targetAudience: 'Desarrolladores que quieran aprender Flutter.',
      imageUrl: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
      category: 'Desarrollo Móvil',
      level: 'Intermedio',
      price: 59.99,
      duration: 20,
      totalLessons: 15,
      totalStudents: 120,
      favorite: 10,
      status: 'Publicado',
      creationDate: DateTime.parse('2025-01-20T15:30:00.000000'),
      lastUpdate: DateTime.parse('2025-02-01T10:00:00.000000'),
      userId: 3,
    ),
    Course(
      id: 3,
      name: 'Machine Learning con Python',
      description: 'Domina el aprendizaje automático con Python.',
      benefits: 'Aprenderás técnicas de machine learning.',
      targetAudience: 'Científicos de datos y desarrolladores.',
      imageUrl: 'https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png',
      category: 'Inteligencia Artificial',
      level: 'Avanzado',
      price: 99.99,
      duration: 40,
      totalLessons: 25,
      totalStudents: 200,
      favorite: 20,
      status: 'Publicado',
      creationDate: DateTime.parse('2024-12-10T09:15:30.000000'),
      lastUpdate: DateTime.parse('2025-01-15T12:45:00.000000'),
      userId: 4,
    ),
  ];
}
